### ISSUE TITLE
明明我配置的是正确的，但提示：java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)       ---|-----APIJSON SYSTEM INFO-----|--- 

### ISSUE THREAD

**Issue by ewsq** [APIJSON/APIJSON-Demo#22]
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)       ---|-----APIJSON SYSTEM INFO-----|--- 

明明我配置的是正常，但提示，这样的错误，搞不清为什么？

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)       ---|-----APIJSON SYSTEM INFO-----|---       
 **环境信息**  
 系统: Windows 11 10.0 
 数据库: MYSQL 8.0.29 
 JDK: 1.8.0_333 amd64 
 APIJSON: 5.1.0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:1971)
	at apijson.orm.AbstractObjectParser.onSQLExecute(AbstractObjectParser.java:898)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:765)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1087)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:568)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:268)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:468)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:117)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:394)
	at apijson.orm.AbstractParser.parse(AbstractParser.java:366)
	at apijson.framework.APIJSONController.parse(APIJSONController.java:92)
	at apijson.framework.APIJSONController.crud(APIJSONController.java:120)
	at apijson.demo.DemoController.crud(DemoController.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:894)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1060)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:962)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)       ---|-----APIJSON SYSTEM INFO-----|---       
 **环境信息**  
 系统: Windows 11 10.0 
 数据库: MYSQL 8.0.29 
 JDK: 1.8.0_333 amd64 
 APIJSON: 5.1.0
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

**Comment by ewsq** [comment]
APIJSON-Demo\APIJSON-Java-Server\APIJSONDemo-Druid

**Comment by ewsq** [comment]
另外，有个localhost 拼写成 localhos 我看 是 apijson-framework 中的问题，原码中已修改了，但是似乎maven仓库中库中并没有修改，所以下载的还是有问题的，出问题的版本是5.1.1

**Comment by ewsq** [comment]
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022-07-09 01:46:27.440: AbstractParser.DEBUG: GET/parseResponse  request = 
{"Moment":{"id":12}}


2022-07-09 01:46:27.441: AbstractParser.DEBUG: GET/parseResponse return response = 
{"Moment":{"id":12},"ok":false,"code":500,"msg":"Access denied for user 'root'@'localhost' (using password: YES)","debug:info|help":"|   \n 浏览器打开以下链接查看解答        \n\n【Google】：\n https://www.google.com/search?q=Access+denied+for+user+%27root%27%40%27localhost%27+%28using+password%3A+YES%29        \n\n【百度】：\n https://www.baidu.com/s?ie=UTF-8&wd=Access+denied+for+user+%27root%27%40%27localhost%27+%28using+password%3A+YES%29\n【APIAuto】： \n http://apijson.cn/api?type=JSON&url=http%3A%2F%2F192.168.10.61%3A8080%2Fget&json=%7B%22Moment%22%3A%7B%22id%22%3A12%7D%7D        \n\n【GitHub】： \n https://www.google.com/search?q=site%3Agithub.com%2FTencent%2FAPIJSON+++Access+denied+for+user+%27root%27%40%27localhost%27+%28using+password%3A+YES%29        \n\n都没找到答案？打开这个链接 \n https://github.com/Tencent/APIJSON/issues/new?assignees=&labels=&template=--bug.md   \n然后提交问题，推荐用以下模板修改，注意要换行保持清晰可读。 \n【标题】：Access denied for user 'root'@'localhost' (using password: YES) \n【内容】：**环境信息**  \n 系统: Windows 11 10.0 \n 数据库: MYSQL 8.0.29 \n JDK: 1.8.0_333 amd64 \n APIJSON: 5.1.0\n\n**问题描述**\nAccess denied for user 'root'@'localhost' (using password: YES) \n\n \n\nPOST http://192.168.10.61:8080/get \n请求 Request JSON：\n ```js \n 请填写，例如 { \"Users\":{} } \n``` \n\n返回结果 Response JSON：\n ```js \n 请填写，例如 { \"Users\": {}, \"code\": 401, \"msg\": \"Users 不允许 UNKNOWN 用户的 GET 请求！\" } \n```","sql:generate|cache|execute|maxExecute":"1|0|1|200","depth:count|max":"1|5","time:start|duration|end|parse|sql":"1657345587425|15|1657345587440|15|0","trace:throw":"java.sql.SQLException","trace:stack":[{"className":"sun.reflect.NativeConstructorAccessorImpl","fileName":"NativeConstructorAccessorImpl.java","lineNumber":-2,"methodName":"newInstance0","nativeMethod":true},{"className":"sun.reflect.NativeConstructorAccessorImpl","fileName":"NativeConstructorAccessorImpl.java","lineNumber":62,"methodName":"newInstance","nativeMethod":false},{"className":"sun.reflect.DelegatingConstructorAccessorImpl","fileName":"DelegatingConstructorAccessorImpl.java","lineNumber":45,"methodName":"newInstance","nativeMethod":false},{"className":"java.lang.reflect.Constructor","fileName":"Constructor.java","lineNumber":423,"methodName":"newInstance","nativeMethod":false},{"className":"apijson.orm.AbstractParser","fileName":"AbstractParser.java","lineNumber":1971,"methodName":"executeSQL","nativeMethod":false},{"className":"apijson.orm.AbstractObjectParser","fileName":"AbstractObjectParser.java","lineNumber":898,"methodName":"onSQLExecute","nativeMethod":false},{"className":"apijson.orm.AbstractObjectParser","fileName":"AbstractObjectParser.java","lineNumber":765,"methodName":"executeSQL","nativeMethod":false},{"className":"apijson.orm.AbstractObjectParser","fileName":"AbstractObjectParser.java","lineNumber":44,"methodName":"executeSQL","nativeMethod":false},{"className":"apijson.orm.AbstractParser","fileName":"AbstractParser.java","lineNumber":1087,"methodName":"onObjectParse","nativeMethod":false},{"className":"apijson.orm.AbstractObjectParser","fileName":"AbstractObjectParser.java","lineNumber":568,"methodName":"onChildParse","nativeMethod":false},{"className":"apijson.orm.AbstractObjectParser","fileName":"AbstractObjectParser.java","lineNumber":268,"methodName":"parse","nativeMethod":false},{"className":"apijson.orm.AbstractObjectParser","fileName":"AbstractObjectParser.java","lineNumber":44,"methodName":"parse","nativeMethod":false},{"className":"apijson.orm.AbstractParser","fileName":"AbstractParser.java","lineNumber":1081,"methodName":"onObjectParse","nativeMethod":false},{"className":"apijson.orm.AbstractParser","fileName":"AbstractParser.java","lineNumber":468,"methodName":"parseResponse","nativeMethod":false},{"className":"apijson.framework.APIJSONParser","fileName":"APIJSONParser.java","lineNumber":117,"methodName":"parseResponse","nativeMethod":false},{"className":"apijson.orm.AbstractParser","fileName":"AbstractParser.java","lineNumber":394,"methodName":"parseResponse","nativeMethod":false},{"className":"apijson.orm.AbstractParser","fileName":"AbstractParser.java","lineNumber":366,"methodName":"parse","nativeMethod":false},{"className":"apijson.framework.APIJSONController","fileName":"APIJSONController.java","lineNumber":92,"methodName":"parse","nativeMethod":false},{"className":"apijson.framework.APIJSONController","fileName":"APIJSONController.java","lineNumber":120,"methodName":"crud","nativeMethod":false},{"className":"apijson.demo.DemoController","fileName":"DemoController.java","lineNumber":65,"methodName":"crud","nativeMethod":false},{"className":"sun.reflect.NativeMethodAccessorImpl","fileName":"NativeMethodAccessorImpl.java","lineNumber":-2,"methodName":"invoke0","nativeMethod":true},{"className":"sun.reflect.NativeMethodAccessorImpl","fileName":"NativeMethodAccessorImpl.java","lineNumber":62,"methodName":"invoke","nativeMethod":false},{"className":"sun.reflect.DelegatingMethodAccessorImpl","fileName":"DelegatingMethodAccessorImpl.java","lineNumber":43,"methodName":"invoke","nativeMethod":false},{"className":"java.lang.reflect.Method","fileName":"Method.java","lineNumber":498,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":197,"methodName":"doInvoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":141,"methodName":"invokeForRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod","fileName":"ServletInvocableHandlerMethod.java","lineNumber":106,"methodName":"invokeAndHandle","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":894,"methodName":"invokeHandlerMethod","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":808,"methodName":"handleInternal","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter","fileName":"AbstractHandlerMethodAdapter.java","lineNumber":87,"methodName":"handle","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":1060,"methodName":"doDispatch","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":962,"methodName":"doService","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":1006,"methodName":"processRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":909,"methodName":"doPost","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":665,"methodName":"service","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":883,"methodName":"service","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":750,"methodName":"service","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":231,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":166,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.tomcat.websocket.server.WsFilter","fileName":"WsFilter.java","lineNumber":53,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":193,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":166,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.RequestContextFilter","fileName":"RequestContextFilter.java","lineNumber":100,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":119,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":193,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":166,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.FormContentFilter","fileName":"FormContentFilter.java","lineNumber":93,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":119,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":193,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":166,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.CharacterEncodingFilter","fileName":"CharacterEncodingFilter.java","lineNumber":201,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":119,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":193,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":166,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.StandardWrapperValve","fileName":"StandardWrapperValve.java","lineNumber":202,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardContextValve","fileName":"StandardContextValve.java","lineNumber":97,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.authenticator.AuthenticatorBase","fileName":"AuthenticatorBase.java","lineNumber":542,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardHostValve","fileName":"StandardHostValve.java","lineNumber":143,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.valves.ErrorReportValve","fileName":"ErrorReportValve.java","lineNumber":92,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardEngineValve","fileName":"StandardEngineValve.java","lineNumber":78,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.connector.CoyoteAdapter","fileName":"CoyoteAdapter.java","lineNumber":343,"methodName":"service","nativeMethod":false},{"className":"org.apache.coyote.http11.Http11Processor","fileName":"Http11Processor.java","lineNumber":374,"methodName":"service","nativeMethod":false},{"className":"org.apache.coyote.AbstractProcessorLight","fileName":"AbstractProcessorLight.java","lineNumber":65,"methodName":"process","nativeMethod":false},{"className":"org.apache.coyote.AbstractProtocol$ConnectionHandler","fileName":"AbstractProtocol.java","lineNumber":888,"methodName":"process","nativeMethod":false},{"className":"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor","fileName":"NioEndpoint.java","lineNumber":1597,"methodName":"doRun","nativeMethod":false},{"className":"org.apache.tomcat.util.net.SocketProcessorBase","fileName":"SocketProcessorBase.java","lineNumber":49,"methodName":"run","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor","fileName":"ThreadPoolExecutor.java","lineNumber":1149,"methodName":"runWorker","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","fileName":"ThreadPoolExecutor.java","lineNumber":624,"methodName":"run","nativeMethod":false},{"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","fileName":"TaskThread.java","lineNumber":61,"methodName":"run","nativeMethod":false},{"className":"java.lang.Thread","fileName":"Thread.java","lineNumber":750,"methodName":"run","nativeMethod":false}]}

**Comment by ewsq** [comment]
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/apijson?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    #username: root
    #password: 12345678
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/apijson?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
      username: root
      password: 12345678
      #type: com.alibaba.druid.pool.DruidDataSource
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true

**Comment by TommyLemon** [comment]
不要在 URI 中指定 schema(模式，又称数据库名)，应该在 DemoSQLConfig 中指定

**Comment by ewsq** [comment]
试了与指不指定这个无关，是读取不到yml文件中的信息，直接使用了默认的连接串。

**Comment by TommyLemon** [comment]
https://github.com/APIJSON/APIJSON-Demo/issues/23#issuecomment-1184143978

**Comment by ewsq** [comment]
嗯嗯，谢谢！！！

是少复写了   createSQLExecutor()


加上

`APIJSONApplication.DEFAULT_APIJSON_CREATOR = new APIJSONCreator<Long>() {
			@Override
			public SQLConfig createSQLConfig() {
				return new DemoSQLConfig();
			}

			@Override
			public SQLExecutor createSQLExecutor() {
				return new DemoSQLExecutor();
			}
		};`

**Comment by TommyLemon** [comment]
可以帮忙提交 PR(Pull Request) 贡献代码谢谢, 开源要大家一起参与贡献才会更美好~
![image](https://user-images.githubusercontent.com/5738175/172325029-b410d90f-0989-4aaa-865d-5a845aca2f1b.png)

https://github.com/Tencent/APIJSON/blob/master/CONTRIBUTING.md#%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%80%E5%AE%9A%E8%A6%81%E8%B4%A1%E7%8C%AE%E4%BB%A3%E7%A0%81
