### ISSUE TITLE
mysql可用但pg异常

### ISSUE THREAD

**Issue by transtone** [APIJSON/APIJSON-Demo#24]
主要是两个问题：
1. Function 不允许 UNKNOWN 用户的 GET 请求！
```shell
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.2)

19:10:53.370 logback [main] INFO  rbs.apijson.Application - Starting Application using Java 1.8.0_242 on stoneWin with PID 11432 (D:\code\hnrr\BE\data-router-apijson\target\classes started by zhou in D:\code\hnrr\BE\data-router-apijson)
19:10:53.373 logback [main] INFO  rbs.apijson.Application - No active profile set, falling back to default profiles: default
19:10:54.542 logback [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s): 8080 (http)
19:10:54.553 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8080"]
19:10:54.553 logback [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
19:10:54.554 logback [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.41]
19:10:54.642 logback [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
19:10:54.643 logback [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 1206 ms
19:10:55.014 logback [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
19:10:55.170 logback [main] INFO  o.a.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["http-nio-8080"]
19:10:55.191 logback [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 8080 (http) with context path ''
19:10:55.202 logback [main] INFO  rbs.apijson.Application - Started Application in 2.261 seconds (JVM running for 2.844)





<<<<<<<<<<<<<<<<<<<<<<<<< APIJSON 开始启动 >>>>>>>>>>>>>>>>>>>>>>>>




开始初始化: Access 权限校验配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

19:10:56.578 logback [main] INFO  c.alibaba.druid.pool.DruidDataSource - {dataSource-1} inited

完成初始化: Access 权限校验配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



开始初始化: Function 远程函数配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


完成初始化: Function 远程函数配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
开始测试: Function 远程函数 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


完成测试: Function 远程函数 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



开始初始化: Request 请求参数校验配置 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

java.lang.IllegalAccessException: Function 不允许 UNKNOWN 用户的 GET 请求！
	at apijson.orm.AbstractVerifier.verifyAllowRole(AbstractVerifier.java:304)
	at apijson.orm.AbstractVerifier.verifyRole(AbstractVerifier.java:274)
	at apijson.orm.AbstractVerifier.verifyAccess(AbstractVerifier.java:267)
	at apijson.orm.AbstractParser.onVerifyRole(AbstractParser.java:546)
	at apijson.orm.AbstractObjectParser.setSQLConfig(AbstractObjectParser.java:739)
	at apijson.orm.AbstractObjectParser.setSQLConfig(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1170)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:566)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.onArrayParse(AbstractParser.java:1309)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:546)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:469)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:117)
	at apijson.framework.APIJSONFunctionParser.init(APIJSONFunctionParser.java:160)
	at apijson.framework.APIJSONFunctionParser.init(APIJSONFunctionParser.java:129)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:92)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)
java.lang.IllegalAccessException: Function 不允许 UNKNOWN 用户的 GET 请求！
	at apijson.orm.AbstractVerifier.verifyAllowRole(AbstractVerifier.java:304)
	at apijson.orm.AbstractVerifier.verifyRole(AbstractVerifier.java:274)
	at apijson.orm.AbstractVerifier.verifyAccess(AbstractVerifier.java:267)
	at apijson.orm.AbstractParser.onVerifyRole(AbstractParser.java:546)
	at apijson.orm.AbstractObjectParser.setSQLConfig(AbstractObjectParser.java:739)
	at apijson.orm.AbstractObjectParser.setSQLConfig(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1170)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:566)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.onArrayParse(AbstractParser.java:1309)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:546)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:469)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:117)
	at apijson.framework.APIJSONFunctionParser.init(APIJSONFunctionParser.java:160)
	at apijson.framework.APIJSONFunctionParser.init(APIJSONFunctionParser.java:129)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:92)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)



<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022-07-20 07:10:56.663: AbstractParser.DEBUG: GET/parseResponse  request = 
{"Function[]":{"Function":{"debug":0},"count":0,"page":0}}


2022-07-20 07:10:56.664: AbstractParser.DEBUG: GET/parseResponse return response = 
{"msg":"Function 不允许 UNKNOWN 用户的 GET 请求！","code":401,"Function[]":{"Function":{"debug":0},"count":0,"page":0},"ok":false}


2022-07-20 07:10:56.664: AbstractParser.DEBUG: GET/parseResponse  endTime = 1658315456663;  duration = 2
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



java.rmi.ServerException: 




 !!!! 查询远程函数异常 !!!
Function 不允许 UNKNOWN 用户的 GET 请求！





	at apijson.framework.APIJSONFunctionParser.onServerError(APIJSONFunctionParser.java:235)
	at apijson.framework.APIJSONFunctionParser.init(APIJSONFunctionParser.java:162)
	at apijson.framework.APIJSONFunctionParser.init(APIJSONFunctionParser.java:129)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:92)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)
java.lang.UnsupportedOperationException: 不允许调用远程函数 countArray !
	at apijson.orm.AbstractFunctionParser.invoke(AbstractFunctionParser.java:157)
	at apijson.orm.AbstractFunctionParser.invoke(AbstractFunctionParser.java:142)
	at apijson.framework.APIJSONFunctionParser.test(APIJSONFunctionParser.java:276)
	at apijson.framework.APIJSONFunctionParser.test(APIJSONFunctionParser.java:241)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:104)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)
java.sql.SQLException: 数据库驱动执行异常SQLException，非 Log.DEBUG 模式下不显示详情，避免泄漏真实模式名、表名等隐私信息
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2031)
	at apijson.orm.AbstractObjectParser.onSQLExecute(AbstractObjectParser.java:896)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:763)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1171)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:566)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.onArrayParse(AbstractParser.java:1309)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:546)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:469)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:117)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:303)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:273)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:118)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)
Caused by: org.postgresql.util.PSQLException: ERROR: column "debug" does not exist
  位置：46
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at apijson.orm.AbstractSQLExecutor.executeQuery(AbstractSQLExecutor.java:1148)
	at apijson.orm.AbstractSQLExecutor.execute(AbstractSQLExecutor.java:276)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:1982)
	... 20 more
java.sql.SQLException: 数据库驱动执行异常SQLException，非 Log.DEBUG 模式下不显示详情，避免泄漏真实模式名、表名等隐私信息
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:2031)
	at apijson.orm.AbstractObjectParser.onSQLExecute(AbstractObjectParser.java:896)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:763)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1171)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:566)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.onArrayParse(AbstractParser.java:1309)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:546)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:266)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:42)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:1081)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:469)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:117)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:303)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:273)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:118)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)
Caused by: org.postgresql.util.PSQLException: ERROR: column "debug" does not exist
  位置：46
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:114)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at apijson.orm.AbstractSQLExecutor.executeQuery(AbstractSQLExecutor.java:1148)
	at apijson.orm.AbstractSQLExecutor.execute(AbstractSQLExecutor.java:276)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:1982)
	... 20 more



<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2022-07-20 07:10:56.697: AbstractParser.DEBUG: GET/parseResponse  request = 
{"Request[]":{"Request":{"@order":"version-,id+","debug":0},"count":0,"page":0}}


2022-07-20 07:10:56.698: AbstractParser.DEBUG: GET/parseResponse return response = 
{"Request[]":{"Request":{"@order":"version-,id+","debug":0},"count":0,"page":0},"ok":false,"code":500,"msg":"数据库驱动执行异常SQLException，非 Log.DEBUG 模式下不显示详情，避免泄漏真实模式名、表名等隐私信息"}


2022-07-20 07:10:56.698: AbstractParser.DEBUG: GET/parseResponse  endTime = 1658315456697;  duration = 31
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>



java.rmi.ServerException: 查询请求校验规则配置异常 !
	at apijson.framework.APIJSONVerifier.onServerError(APIJSONVerifier.java:485)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:306)
	at apijson.framework.APIJSONVerifier.initRequest(APIJSONVerifier.java:273)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:118)
	at apijson.framework.APIJSONApplication.init(APIJSONApplication.java:50)
	at rbs.apijson.Application.main(Application.java:56)

完成初始化: Request 请求参数校验校验配置 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>


```

**Comment by transtone** [comment]
对照了mysql的sql，发现mysql的这四个表都有debug字段 `Access`, `Document`,`Function`,`Request` ，而pg中只有 `Access`表有。

**Comment by TommyLemon** [comment]
PostgreSQL 的表，postgres_sys.sql（所有表 dump 汇总为一个 SQL 文件）两年没有同步了，建议改用 single 或  single-no-schema 目录下的
https://github.com/APIJSON/APIJSON-Demo/tree/master/PostgreSQL
