### ISSUE TITLE
这个demo启动有报错，好坑

### ISSUE THREAD

**Issue by minshiwu** [APIJSON/APIJSON-Demo#4]
这demo工程，默认使用apijson-framework，可以做到无任何配置即可体验apijson的各种能力。

```xml
		<!-- 需要的 APIJSON 相关依赖 -->
		<dependency>
			<groupId>com.github.APIJSON</groupId>
			<artifactId>apijson-framework</artifactId>
			<version>LATEST</version>
		</dependency>
```

但是这个apijson-framework工程里面写了很多test代码。比如下面这种。比如下面这个`plus`自定义函数，触发就会报错。

```java
Log.i(TAG, "plus(1,-2) = " + function.invoke("plus(i0,i1)", request));
		Log.i(TAG, "count([1,2,4,10]) = " + function.invoke("countArray(array)", request));
```
这里也会报错。搞不懂这个apijson-framework工程这么搞意义是啥。

```java
		try {
			request = JSON.parseObject("{\"Comment\":{\"id\":0, \"userId\":0, \"momentId\":0, \"content\":\"apijson\"}}");
			Log.d(TAG, "test  verifyRequest = " + AbstractVerifier.verifyRequest(RequestMethod.POST, "", JSON.parseObject(requestString), request, APIJSON_CREATOR));
		} catch (Exception e) {
			e.printStackTrace();
		}
```

但是基于这个工程 `apijson-java-server`启动，并且刷入mysql目录下所有表。启动有报错，具体2类错误

1.  Function表里面很多函数，没有在`apijson.framework.APIJSONFunctionParser`中定义。报错。自己实现后解决。
2.  还有一个如下的校验错误。`apijson.framework.APIJSONVerifier#testStructure`

```
java.lang.IllegalArgumentException: POST请求，Comment 里面不能缺少 momentId 等[userId,momentId,content]内的任何字段！
	at apijson.orm.AbstractVerifier.parse(AbstractVerifier.java:794)
	at apijson.orm.AbstractVerifier.verifyRequest(AbstractVerifier.java:541)
	at apijson.orm.AbstractVerifier$1.onParseJSONObject(AbstractVerifier.java:579)
	at apijson.orm.AbstractVerifier.parse(AbstractVerifier.java:835)
	at apijson.orm.AbstractVerifier.verifyRequest(AbstractVerifier.java:541)
	at apijson.orm.AbstractVerifier.verifyRequest(AbstractVerifier.java:505)
	at apijson.orm.AbstractVerifier.verifyRequest(AbstractVerifier.java:491)
	at apijson.framework.APIJSONVerifier.testStructure(APIJSONVerifier.java:396)
```

**Comment by TommyLemon** [comment]
这个是启动时自检，看 APIJSON 对请求参数的校验是否生效，不影响使用，只要最后显示 “APIJSON 已启动” 就行了。
不过确实让挺多人困惑，以为时启动出了问题，后面我们优化下，感谢反馈

**Comment by TommyLemon** [comment]
其实默认是要配置的，Access 表对应权限配置、Request 表对应参数校验配置。
APIJSONDemo 关掉了所有校验，不需要以上配置，只需要数据库配置正确即可体验校验之外的所有功能。
https://github.com/APIJSON/APIJSON-Demo/tree/master/APIJSON-Java-Server

**Comment by TommyLemon** [comment]
已更新，优化了启动时自检
https://github.com/APIJSON/APIJSON-Demo/releases/tag/4.6.3
